services:
  - type: web
    name: vms-backend
    env: python
    rootDirectory: backend
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        fromDatabase:
          name: vms-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: vms-db
    databaseName: vms
    user: vms_user
